### ISSUE TITLE
When scanning an item with synchronization errors, the scanned text will flash.

### ISSUE THREAD

**Issue by NakiriFox** [Test-Account666/LethalCompany-GoodItemScan#1]
For example, scanning the "ghost item" generated when the host uses a two handed mod.

**Comment by NakiriFox** [comment]
Or scan the "invisible flashlight" which generated by using the scroll wheel to switch the item slot at the last second of interaction when the player places the open flashlight into the item cabinet.

**Comment by Test-Account666** [comment]
Can you show me a video of this?

**Comment by NakiriFox** [comment]
I seem to have solved this problem, the issue maybe caused by simultaneously using  the GoodItemScan and "FixPersonalScanner" from GeneralImprovements.

Perhaps you can add a tip on the MOD introduction page？
