### ISSUE TITLE
[Suggestion] Total item count

### ISSUE THREAD

**Issue by viiuan** [Test-Account666/LethalCompany-GoodItemScan#2]
Trying out this mod hoping it will improve performance over ScannerFix, but I do like the total item count it shows when scanning multiple items. Could this be added here?

**Comment by Test-Account666** [comment]
Can you explain this in more detail?

**Comment by viiuan** [comment]
Here it is in the mod's thumbnail:
![image](https://gcdn.thunderstore.io/live/repository/icons/QERT2002-ScannerFix-1.2.0.png.256x256_q95_crop.jpg)
The "Count: 24" is what I mean.

**Comment by Test-Account666** [comment]
So, I looked at this a while ago and decided the effort is not worth it
