### ISSUE TITLE
Total amount of money racks up way too slow and laggy

### ISSUE THREAD

**Issue by broken-usb** [Test-Account666/LethalCompany-GoodItemScan#3]
While using this mod whenever i scan either a single item or multiple items, the amount of time it takes to show the total amount of money that i scanned takes excruciating long sometimes and the animation for it is pretty laggy.

https://github.com/user-attachments/assets/60b22d2a-961c-42ee-a214-e1cb23807520

(video got buggy on the start, plays normally after 0:10)

**Comment by broken-usb** [comment]
Profile code: `01910972-5095-cfc9-8e0b-2f1124afa816`
Log: [LogOutput.log](https://github.com/user-attachments/files/16444128/LogOutput.log) (sadly i don't have the debug logging of the mod enabled, but i can enable it if you want/need me to)

**Comment by Test-Account666** [comment]
I don't see the laggy part tbh 😅

**Comment by Test-Account666** [comment]
The counting always has been slow. My mod actually speeds it up the more items you scanned at once

**Comment by broken-usb** [comment]
What I meant to say is that in the vanilla version, the total money amount increases smoothly with the sound playing nicely. But with GIS, the numbers increase in a choppy way, and the sound is a lot slower.

Vanilla Scan:

https://github.com/user-attachments/assets/e3a18e77-4907-4dcb-9349-5261c2c40bc7

GoodItemScan:

https://github.com/user-attachments/assets/eb6330c2-d94b-4a75-a26c-49073b4ea52c

(I recommend turning the volume up so you can better listen to it, and ignore the cruiser in the back)

**Comment by Krevous** [comment]
Also would be cool to have an option in config which controls the speed of counting

**Comment by Test-Account666** [comment]
Version 1.6.0 gives you a config option for this.

Set the `Total Add Wait Multiplier` value to `48` for a vanilla-ish experience
