### ISSUE TITLE
Sometimes scan items text appear in front of you when they are behind you.

### ISSUE THREAD

**Issue by NakiriFox** [Test-Account666/LethalCompany-GoodItemScan#5]
Has GoodItemScan fixed this issue？I'm not entirely sure because this issue occasionally happen and occasionally doesn't.

This mod👇 fixes this issue, perhaps you can refer to it?
https://thunderstore.io/c/lethal-company/p/TheSecretDev/Unlimited_Scan/

**Comment by NakiriFox** [comment]
My config settings
![QQ_1722624265637](https://github.com/user-attachments/assets/a40c44ec-bad5-4eda-a7f6-e1d48ad87627)
![QQ_1722624272004](https://github.com/user-attachments/assets/f9e993b1-6b46-404b-88bf-105c37b13df7)

**Comment by Test-Account666** [comment]
It should not be possible to scan any items behind you

**Comment by Test-Account666** [comment]
Reason for this is the fact that the calculated distance would be in the negatives otherwise

**Comment by NakiriFox** [comment]
Sorry, I edited the vague issue description.

The correct description can be found in another issue I previously initiated👇
https://github.com/ButteryStancakes/ButteryFixes/issues/7

**Comment by Test-Account666** [comment]
> Sorry, I edited the vague issue description.
> 
> The correct description can be found in another issue I previously initiated👇
> https://github.com/ButteryStancakes/ButteryFixes/issues/7

As I said:
This shouldn't happen with GoodItemScan.

Unless you're using another scan mod along side of it

**Comment by NakiriFox** [comment]
When this issue occurred, I did not use Unlimited_Scan and  GeneralImprovements's FixPersonalScanner.

Let me test it tomorrow. I will reopen the issue once this situation occurs again.
